import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { GlobalNavigationBar } from '@/components/layout/gnb';
import { QueryProvider } from '@/providers/query-provider';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { LoginAlertModal } from '@/components/ui/login-alert-modal';

import { getMyProfileAction } from '@/actions/auth/auth-actions';
import { AuthProvider } from '@/providers/auth-provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // SSR 단계에서 서버용 API를 통해 유저 정보 가져오기
  const userResult = await getMyProfileAction();
  const initialUser = userResult?.data || null;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <AuthProvider initialUser={initialUser}>
            <GlobalNavigationBar initialUser={initialUser} />

            <main className="flex-1 flex flex-col sm:max-w-7xl sm:mx-auto w-full">
              <NuqsAdapter>{children}</NuqsAdapter>
            </main>

            <LoginAlertModal />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
